// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBEYet20Qclds33sD2VVtnL81AJmbS7PY',
    appId: '1:897823893089:web:66ba4f18697c36d5166c20',
    messagingSenderId: '897823893089',
    projectId: 'my-pcp-b51f1',
    authDomain: 'my-pcp-b51f1.firebaseapp.com',
    storageBucket: 'my-pcp-b51f1.firebasestorage.app',
    measurementId: 'G-WG65HRD672',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkh7AtdImtF6xcEERDqZtSEJO3rAuTskk',
    appId: '1:897823893089:android:beaa3b14730496f1166c20',
    messagingSenderId: '897823893089',
    projectId: 'my-pcp-b51f1',
    storageBucket: 'my-pcp-b51f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYK0N0_jkuNoThPo8gyMWMcnN29vJocUc',
    appId: '1:897823893089:ios:15cfd309ef1226e6166c20',
    messagingSenderId: '897823893089',
    projectId: 'my-pcp-b51f1',
    storageBucket: 'my-pcp-b51f1.firebasestorage.app',
    iosBundleId: 'com.example.personPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYK0N0_jkuNoThPo8gyMWMcnN29vJocUc',
    appId: '1:897823893089:ios:15cfd309ef1226e6166c20',
    messagingSenderId: '897823893089',
    projectId: 'my-pcp-b51f1',
    storageBucket: 'my-pcp-b51f1.firebasestorage.app',
    iosBundleId: 'com.example.personPlan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBEYet20Qclds33sD2VVtnL81AJmbS7PY',
    appId: '1:897823893089:web:aae99a70533d7317166c20',
    messagingSenderId: '897823893089',
    projectId: 'my-pcp-b51f1',
    authDomain: 'my-pcp-b51f1.firebaseapp.com',
    storageBucket: 'my-pcp-b51f1.firebasestorage.app',
    measurementId: 'G-CVNEHMRPVC',
  );
}
